-- V11: Add insurance companies and professional pricing
-- Adds insurance companies table, professional pricing, and many-to-many relationship

-- 1. Create insurance_companies table
CREATE TABLE insurance_companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    code VARCHAR(50) NOT NULL UNIQUE,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Add private consultation price to professionals
ALTER TABLE professionals ADD COLUMN private_consultation_price DECIMAL(10,2);

-- 3. Create many-to-many relationship table
CREATE TABLE professional_insurances (
    professional_id BIGINT NOT NULL,
    insurance_company_id BIGINT NOT NULL,
    PRIMARY KEY (professional_id, insurance_company_id),
    FOREIGN KEY (professional_id) REFERENCES professionals(id) ON DELETE CASCADE,
    FOREIGN KEY (insurance_company_id) REFERENCES insurance_companies(id) ON DELETE CASCADE
);

-- 4. Create indexes for better performance
CREATE INDEX idx_prof_insurances_professional ON professional_insurances(professional_id);
CREATE INDEX idx_prof_insurances_insurance ON professional_insurances(insurance_company_id);

-- 5. Insert initial insurance companies data
INSERT INTO insurance_companies (name, code) VALUES
('OSDE', 'OSDE'),
('Galeno', 'GAL'),
('APROSS', 'APR'),
('Swiss Medical', 'SWM'),
('Medicus', 'MED'),
('IOMA', 'IOMA'),
('PAMI', 'PAMI'),
('Sancor Salud', 'SAN');
