/* V16: Agregar soporte para procedimientos y duración variable de turnos */

/* 1. Agregar campo duration_minutes a appointments */
ALTER TABLE appointments ADD COLUMN duration_minutes INT DEFAULT 30;

/* 2. Crear tabla de procedimientos */
CREATE TABLE procedures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL,
    specialty_id BIGINT,
    name VARCHAR(200) NOT NULL,
    duration_minutes INT NOT NULL DEFAULT 30,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (specialty_id) REFERENCES specialties(id)
);

CREATE INDEX idx_procedures_tenant ON procedures(tenant_id);
CREATE INDEX idx_procedures_specialty ON procedures(specialty_id);

/* 3. Agregar referencia de procedure en appointments (opcional) */
ALTER TABLE appointments ADD COLUMN procedure_id BIGINT;
ALTER TABLE appointments ADD CONSTRAINT fk_appointments_procedure
    FOREIGN KEY (procedure_id) REFERENCES procedures(id);

